### PR TITLE
Update dependencies and use only yarn.lock

### PR DESCRIPTION
**Pull request by ansidev**

### CODE REVIEW

**Comment by matheusgrieger** [comment]
Everything looks good! But why did you remove `package-lock.json`? There are no problems in keeping `yarn.lock`, but there is a fair amount of people using npm instead of yarn.

**Comment by ansidev** [comment]
@matheusgrieger I don't recommend using both pack manager, just one, but it 's up to you. I can add `package-lock.json` again.

**Comment by matheusgrieger** [comment]
I would prefer that, yes.

As npm is currently the "standard" (considering it is installed by default with Node), I assume is what most people use.

Aside from that, everything else looks great, and what you changed is really nice, thank you.

**Comment by ansidev** [comment]
@matheusgrieger Done!

**Comment by ansidev** [comment]
@matheusgrieger You are welcome!

**Comment by matheusgrieger** [comment]
I will be publishing a new version soon. Again, thank you.

**Pull request merged**
